### ISSUE TITLE
Snippets autocomplete doesn't appear

### ISSUE THREAD

**Issue by max-bertinetti** [DAmNRelentless/vscode-keepachangelog#1]
**Describe the bug**
Autocomplete snippets doesn't appear on VSCODE

**To Reproduce**
1. Create a CHANGELOG.md file in a project
2. Try to use a snippet es. changelog-init

**Expected behavior**
Suggestion must appear above the text

**Screenshots & Logs**
If applicable, add screenshots and/or logs to help explain your problem.

**Versions (please complete the following information):**
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-7625-generic

**Additional extensions**
Vue Snippets (sdras.vue-vscode-snippets)
Vuetify-vscode
Vscode Nestjs Snippets (ashinzekene)

**Comment by max-bertinetti** [comment]
@DAmNRelentless
What's the meaning of creating a template called BUG that create a bug label and then remove the bug label, assign the ticket to requester?

You have only two templates: BUG report and FEATURE request.......

**Comment by max-bertinetti** [comment]
Actually CTRL + space make it works.

**Comment by rlnt** [comment]
> @DAmNRelentless
> What's the meaning of creating a template called BUG that create a bug label and then remove the bug label, assign the ticket to requester?
> 
> You have only two templates: BUG report and FEATURE request.......

No need to be rude. It was automatically removed by GitHub since I deleted the label completely.
We have organization standard labels for all our repositories but this repository is so old, that the labels didn't exist yet so I added them manually.

**Comment by rlnt** [comment]
For future reference and clarification:
This issue was discussed on our support Discord server.
After updating my personal VSCode to the version mentioned in the issue, I was not able to reproduce this issue.
I personally have Windows 10 as my OS and couldn't test it on Linux.

I gave the issue submitter some steps to maybe find a workaround and it seems like the solution to press CTRL + space works for getting the snippet suggestions. I can't tell if it's due to a bug in VSCode on Linux or any conflicting extension.

The issue is hereby closed and no fixes will be applied to the repository since it's not reproducible.
